import type { Metadata } from 'next'
import Link from 'next/link'
import { Search } from 'lucide-react'
import { GlobalSearchForm } from '@/components/forms/global-search-form'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { searchEverything } from '@/lib/search'
export const metadata: Metadata = { title: 'Search', description: 'Search complaint guides, templates, schemes, documents and official resources.' }
export default async function Page({ searchParams }: { searchParams?: Promise<{ q?: string }> | { q?: string } }){ const params=await Promise.resolve(searchParams||{}); const q=typeof params.q==='string'?params.q:''; const results=await searchEverything(q,30); return <main className="bg-slate-50"><section className="mx-auto max-w-5xl px-4 py-12"><Badge>Universal Search</Badge><h1 className="mt-3 text-4xl font-black">Search HaqSathi AI</h1><p className="mt-3 text-slate-600">Complaint formats, refund guides, UPI help, templates, resources aur schemes ek jagah search karo.</p><div className="mt-6"><GlobalSearchForm/></div>{q?<p className="mt-6 text-sm font-semibold text-slate-600">Results for: <span className="text-slate-950">{q}</span></p>:<p className="mt-6 text-sm text-slate-600">Try: “Flipkart refund”, “UPI wrong transfer”, “income certificate”, “Bihar scholarship”.</p>}<div className="mt-6 grid gap-4">{results.map((item)=><Card key={`${item.type}-${item.href}-${item.title}`}><CardHeader><div className="flex items-center gap-2"><Search className="h-4 w-4 text-emerald-700"/><span className="text-xs font-bold uppercase tracking-wider text-emerald-700">{item.type}</span></div><CardTitle><Link href={item.href} className="hover:text-emerald-700">{item.title}</Link></CardTitle></CardHeader><CardContent><p className="text-sm text-slate-600">{item.description}</p><Link href={item.href} className="mt-3 inline-flex text-sm font-bold text-emerald-700">Open →</Link></CardContent></Card>)}{q&&!results.length?<Card><CardContent className="p-6 text-sm text-slate-600">No result found. Simple keyword try karo ya AI Chat use karo.</CardContent></Card>:null}</div></section></main> }
