import PDFDocument from 'pdfkit'

export type ComplaintDraftJson = {
  shortComplaint?: string
  formalEmail?: string
  consumerHelplineFormat?: string
  companySupportMessage?: string
  followUpMessage?: string
  legalNoticeStyleDraft?: string
  checklist?: string[]
  nextSteps?: string[]
  disclaimer?: string
}

export function complaintDraftToText(draft: ComplaintDraftJson) {
  const sections: [string, string | string[] | undefined][] = [
    ['Short Complaint', draft.shortComplaint],
    ['Formal Email', draft.formalEmail],
    ['Consumer Helpline Format', draft.consumerHelplineFormat],
    ['Company Support Message', draft.companySupportMessage],
    ['Follow-up Message', draft.followUpMessage],
    ['Legal Notice Style Draft', draft.legalNoticeStyleDraft],
    ['Checklist', draft.checklist],
    ['Next Steps', draft.nextSteps],
    ['Disclaimer', draft.disclaimer]
  ]

  return sections
    .filter(([, value]) => Array.isArray(value) ? value.length > 0 : Boolean(value))
    .map(([title, value]) => `${title}\n${Array.isArray(value) ? value.map((v) => `- ${v}`).join('\n') : value}`)
    .join('\n\n')
}

export async function createComplaintPdf(input: {
  title: string
  subtitle: string
  draft: ComplaintDraftJson
}) {
  const doc = new PDFDocument({ size: 'A4', margin: 48, info: { Title: input.title, Author: 'HaqSathi AI' } })
  const chunks: Buffer[] = []
  doc.on('data', (chunk: Buffer) => chunks.push(chunk))

  doc.fontSize(20).text(input.title, { align: 'left' })
  doc.moveDown(0.4)
  doc.fontSize(10).fillColor('#475569').text(input.subtitle)
  doc.moveDown(1)
  doc.fillColor('#0f172a')

  const text = complaintDraftToText(input.draft)
  for (const block of text.split('\n\n')) {
    const [heading, ...body] = block.split('\n')
    doc.fontSize(13).fillColor('#0f172a').text(heading, { underline: true })
    doc.moveDown(0.25)
    doc.fontSize(10).fillColor('#334155').text(body.join('\n'), { lineGap: 4 })
    doc.moveDown(0.9)
  }

  doc.fontSize(8).fillColor('#64748b').text('Generated by HaqSathi AI. This is guidance, not legal advice. Verify details on official portals/support channels.', 48, 780, { width: 500 })
  doc.end()

  await new Promise<void>((resolve) => doc.on('end', resolve))
  return Buffer.concat(chunks)
}
