import type { Metadata } from 'next'
import Link from 'next/link'
import { SUPPORT_EMAIL, LEGAL_JURISDICTION, LEGAL_LAST_UPDATED } from '@/lib/content/site-contact'

export const dynamic = 'force-static'
export const revalidate = 86400

export const metadata: Metadata = { title: 'Terms of Service', description: 'Terms for using HaqSathi AI responsibly.' }

export default function Page() {
  return (
    <main className="bg-slate-50">
      <article className="mx-auto max-w-4xl px-4 py-12">
        <div className="rounded-[2rem] border bg-white p-6 shadow-soft sm:p-8">
          <p className="text-sm font-black uppercase tracking-wider text-emerald-700">Legal</p>
          <h1 className="mt-2 text-4xl font-black text-slate-950">Terms of Service</h1>
          <p className="mt-2 text-sm font-semibold text-slate-500">Last updated: {LEGAL_LAST_UPDATED}</p>
          <div className="mt-6 space-y-7 text-sm leading-7 text-slate-700 sm:text-base">
            <p>By using HaqSathi AI, you agree to these terms.</p>
            <section><h2 className="text-2xl font-black text-slate-950">1. What HaqSathi AI is</h2><p className="mt-2">HaqSathi AI is a guidance and drafting tool that helps you prepare complaint drafts, evidence checklists, follow-up messages, scheme suggestions and document checklists. <b>We are not a government department, bank, court, law firm, or any official authority</b>, and we do not file complaints, submit applications, or represent you before any authority.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">2. Eligibility</h2><p className="mt-2">You must be at least 18 years old to create an account and use HaqSathi AI.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">3. Your account</h2><p className="mt-2">You are responsible for keeping your login credentials secure and for activity under your account. Notify us immediately if you suspect unauthorized access.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">4. Your content and responsibilities</h2><p className="mt-2">You are responsible for the accuracy of information you enter. Do not enter OTPs, passwords, full card numbers, UPI PINs, or other secret credentials — HaqSathi AI never needs these, and entering them is at your own risk.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">5. AI-generated content</h2><p className="mt-2">Drafts, scores, suggestions and checklists are generated by AI models and may contain errors, outdated information, or inaccuracies. <b>Always verify any output against the official portal, your bank, the relevant company, or a qualified professional before relying on it or submitting it anywhere.</b></p></section>
            <Section title="6. Subscription plans and payments" items={['Free: limited usage as shown on the Pricing page.', 'Pro / Family / Agent: paid monthly subscriptions billed via Razorpay in INR; features may change with notice.', 'Subscriptions renew automatically each billing cycle unless cancelled before renewal.', 'Cancellation takes effect at the end of the current billing period.', `Refund questions can be sent to ${SUPPORT_EMAIL}; Razorpay processing timelines may apply.`]} />
            <Section title="7. Acceptable use" items={['Do not use HaqSathi AI for unlawful purposes, fraudulent claims, harassment or impersonation.', 'Do not reverse-engineer, scrape, or overload the platform.', 'Do not share your account in violation of plan limits.']} />
            <section><h2 className="text-2xl font-black text-slate-950">8. Intellectual property</h2><p className="mt-2">The HaqSathi AI name, logo, design and underlying software belong to us. Drafts generated for your own case are yours to use; you may not resell or redistribute the platform itself.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">9. Limitation of liability</h2><p className="mt-2">HaqSathi AI is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of any kind. To the maximum extent permitted by law, we are not liable for any loss arising from reliance on AI-generated content, decisions made based on it, or outcomes of complaints/applications you file using it.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">10. Termination</h2><p className="mt-2">We may suspend or terminate accounts that violate these terms. You may delete your account at any time.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">11. Governing law and disputes</h2><p className="mt-2">These terms are governed by the laws of India. Disputes are subject to the jurisdiction of the courts in {LEGAL_JURISDICTION}, India.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">12. Changes to these terms</h2><p className="mt-2">We may update these terms periodically; continued use after changes means you accept the update.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">13. Contact</h2><p className="mt-2">Questions about these terms: <a className="font-black text-emerald-700 underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p></section>
          </div>
          <div className="mt-8 flex flex-wrap gap-3"><Link href="/pricing" className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">View Pricing</Link><Link href="/" className="rounded-xl border px-5 py-3 font-semibold">Home</Link></div>
        </div>
      </article>
    </main>
  )
}

function Section({ title, items }: { title: string; items: string[] }) {
  return <section><h2 className="text-2xl font-black text-slate-950">{title}</h2><ul className="mt-3 list-disc space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>
}
