export const authorityDirectorySeeds = [
  { slug: 'national-consumer-helpline', name: 'National Consumer Helpline', category: 'CONSUMER', state: null, escalationLevel: 'BASIC', description: 'Consumer complaints ke initial guidance, grievance registration, tracking aur document upload ke liye Department of Consumer Affairs public portal.', email: null, phone: '1915', website: 'https://consumerhelpline.gov.in/', address: null, verified: true },
  { slug: 'e-jagriti-consumer-commission', name: 'e-Jagriti / Consumer Commission Filing', category: 'CONSUMER', state: null, escalationLevel: 'ESCALATION', description: 'Consumer commission filing, case status and related consumer dispute services ke liye official portal reference.', email: null, phone: null, website: 'https://e-jagriti.gov.in/', address: null, verified: true },
  { slug: 'rbi-integrated-ombudsman', name: 'RBI Integrated Ombudsman / CMS', category: 'BANKING', state: null, escalationLevel: 'ESCALATION', description: 'Bank/NBFC/payment complaints me regulated entity ke response/waiting period ke baad RBI escalation option.', email: null, phone: '14448', website: 'https://cms.rbi.org.in/', address: null, verified: true },
  { slug: 'cybercrime-portal-india', name: 'National Cyber Crime Reporting Portal', category: 'CYBER', state: null, escalationLevel: 'URGENT', description: 'Cyber fraud, UPI scam, online financial fraud and other cybercrime reporting ke liye official portal.', email: null, phone: '1930', website: 'https://cybercrime.gov.in/', address: null, verified: true },
  { slug: 'npci-upi-dispute', name: 'NPCI UPI Complaint / Dispute Resource', category: 'UPI', state: null, escalationLevel: 'REFERENCE', description: 'UPI complaint, dispute status and escalation flow understand karne ke liye NPCI reference page.', email: null, phone: null, website: 'https://www.npci.org.in/upi-complaint', address: null, verified: true },
  { slug: 'uidai-aadhaar-help', name: 'UIDAI Aadhaar Help', category: 'DOCUMENT', state: null, escalationLevel: 'BASIC', description: 'Aadhaar update, status, enrollment center, PVC card and authentication related official help.', email: null, phone: '1947', website: 'https://uidai.gov.in/', address: null, verified: true },
  { slug: 'digilocker', name: 'DigiLocker', category: 'DOCUMENT', state: null, escalationLevel: 'BASIC', description: 'Issued documents, certificates and digital document wallet ke liye official DigiLocker service.', email: null, phone: null, website: 'https://www.digilocker.gov.in/', address: null, verified: true },
  { slug: 'national-scholarship-portal', name: 'National Scholarship Portal', category: 'SCHEME', state: null, escalationLevel: 'BASIC', description: 'Central scholarship discovery, application and status reference for eligible students.', email: null, phone: null, website: 'https://scholarships.gov.in/', address: null, verified: true },
  { slug: 'bihar-scholarship-portal', name: 'Bihar Post Matric Scholarship Portal', category: 'SCHEME', state: 'Bihar', escalationLevel: 'BASIC', description: 'Bihar post-matric scholarship application/status related official portal reference.', email: null, phone: null, website: 'https://pmsonline.bih.nic.in/', address: null, verified: true },
  { slug: 'up-scholarship-portal', name: 'UP Scholarship Portal', category: 'SCHEME', state: 'Uttar Pradesh', escalationLevel: 'BASIC', description: 'UP scholarship registration, renewal, status and institute verification reference.', email: null, phone: null, website: 'https://scholarship.up.gov.in/', address: null, verified: true },
  { slug: 'ayushman-bharat-beneficiary', name: 'Ayushman Bharat Beneficiary Portal', category: 'HEALTH', state: null, escalationLevel: 'BASIC', description: 'Ayushman card eligibility and beneficiary details verify karne ke liye official portal.', email: null, phone: '14555', website: 'https://beneficiary.nha.gov.in/', address: null, verified: true },
  { slug: 'eshram', name: 'e-SHRAM Portal', category: 'SCHEME', state: null, escalationLevel: 'BASIC', description: 'Unorganised worker registration and e-SHRAM card related official service.', email: null, phone: null, website: 'https://eshram.gov.in/', address: null, verified: true },
  { slug: 'pm-kisan', name: 'PM-KISAN Portal', category: 'SCHEME', state: null, escalationLevel: 'BASIC', description: 'PM-KISAN beneficiary status, farmer registration and instalment status reference.', email: null, phone: null, website: 'https://pmkisan.gov.in/', address: null, verified: true },
  { slug: 'passport-seva', name: 'Passport Seva', category: 'DOCUMENT', state: null, escalationLevel: 'BASIC', description: 'Passport application, appointment and status related official portal.', email: null, phone: null, website: 'https://www.passportindia.gov.in/', address: null, verified: true },
  { slug: 'epfo-grievance', name: 'EPFO Grievance Management System', category: 'EMPLOYMENT', state: null, escalationLevel: 'ESCALATION', description: 'PF/UAN/pension related grievance registration and status reference.', email: null, phone: null, website: 'https://epfigms.gov.in/', address: null, verified: true }
]
