import Link from 'next/link'
import type { ReactNode } from 'react'

const adminLinks = [
  ['/admin', 'Overview'],
  ['/admin/final-qa', 'Final QA'],
  ['/admin/route-inventory', 'Route Inventory'],
  ['/admin/release-notes', 'Release Notes'],
  ['/admin/growth', 'Growth'],
  ['/admin/ops', 'Ops Center'],
  ['/admin/data-quality', 'Data Quality'],
  ['/admin/source-verification', 'Source Verification'],
  ['/admin/production-qa', 'Production QA'],
  ['/admin/backup-restore', 'Backup Restore'],
  ['/admin/security-hardening', 'Security Hardening'],
  ['/admin/seo-audit', 'SEO Audit'],
  ['/admin/build-center', 'Build Center'],
  ['/admin/env-health', 'Env Health'],
  ['/admin/feature-flags', 'Feature Flags'],
  ['/admin/incidents', 'Incidents'],
  ['/admin/support-macros', 'Support Macros'],
  ['/admin/partner-leads', 'Partner Leads'],
  ['/admin/moderation', 'Moderation'],
  ['/admin/experiments', 'Experiments'],
  ['/admin/playbooks', 'Playbooks'],
  ['/admin/localization', 'Localization'],
  ['/admin/print-jobs', 'Print Jobs'],
  ['/admin/metrics-snapshots', 'Metric Snapshots'],
  ['/admin/link-checks', 'Link Checks'],
  ['/admin/prompt-lab', 'Prompt Lab'],
  ['/admin/content-ideas', 'Content Ideas'],
  ['/admin/seo-keywords', 'SEO Keywords'],
  ['/admin/revenue-insights', 'Revenue'],
  ['/admin/authority-directory', 'Authority Directory'],
  ['/admin/state-guides', 'State Guides'],
  ['/admin/success-stories', 'Success Stories'],
  ['/admin/case-intelligence', 'Case Intel'],
  ['/admin/users', 'Users'],
  ['/admin/complaints', 'Complaints'],
  ['/admin/seo-pages', 'SEO Pages'],
  ['/admin/schemes', 'Schemes'],
  ['/admin/blog', 'Blog'],
  ['/admin/templates', 'Templates'],
  ['/admin/resources', 'Resources'],
  ['/admin/filing-guides', 'Filing Guides'],
  ['/admin/ai-reviews', 'AI Reviews'],
  ['/admin/feedback', 'Feedback'],
  ['/admin/audit', 'Audit Log'],
  ['/admin/compliance', 'Compliance'],
  ['/admin/notifications', 'Notifications'],
  ['/admin/launch', 'Launch'],
  ['/admin/emails', 'Emails'],
  ['/admin/backups', 'Backups'],
  ['/admin/payments', 'Payments'],
  ['/admin/invoices', 'Invoices'],
  ['/admin/support', 'Support'],
  ['/admin/analytics', 'Analytics']
]

export function AdminShell({ children }: { children: ReactNode }) {
  return <main className="bg-slate-50"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 lg:grid-cols-[240px_1fr]"><aside className="h-fit rounded-3xl border bg-white p-4 shadow-soft"><p className="px-3 text-xs font-bold uppercase tracking-wider text-slate-500">Admin</p><nav className="mt-3 grid gap-1">{adminLinks.map(([href, label]) => <Link key={href} href={href} className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">{label}</Link>)}</nav></aside><section>{children}</section></div></main>
}
