import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'fs'
import { join, relative, sep } from 'path'

const appDir = join(process.cwd(), 'app')
const outDir = join(process.cwd(), 'docs')
const routes: string[] = []

function walk(dir: string) {
  for (const item of readdirSync(dir)) {
    const full = join(dir, item)
    const stat = statSync(full)
    if (stat.isDirectory()) walk(full)
    if (stat.isFile() && item === 'page.tsx') {
      const rel = relative(appDir, dir).split(sep).join('/')
      const route = '/' + rel.replace(/\/page$/, '')
      routes.push(route === '/.' ? '/' : route)
    }
  }
}

walk(appDir)
routes.sort()
if (!existsSync(outDir)) mkdirSync(outDir)
const md = `# HaqSathi AI Route Inventory\n\nGenerated by \`npm run route:inventory\`.\n\nTotal pages: ${routes.length}\n\n${routes.map((r) => `- \`${r}\``).join('\n')}\n`
writeFileSync(join(outDir, 'ROUTE_INVENTORY.md'), md)
console.log(`✅ Route inventory written: docs/ROUTE_INVENTORY.md (${routes.length} pages)`) 
