import type { Metadata } from 'next'
import Link from 'next/link'
import { FraudEscalationAlert } from '@/components/content/fraud-escalation-alert'

export const dynamic = 'force-static'
export const revalidate = 86400

export const metadata: Metadata = { title: 'Disclaimer', description: 'HaqSathi AI is guidance, not legal advice or an official authority.' }

export default function Page() {
  return (
    <main className="bg-slate-50">
      <article className="mx-auto max-w-4xl px-4 py-12">
        <div className="rounded-[2rem] border bg-white p-6 shadow-soft sm:p-8">
          <p className="text-sm font-black uppercase tracking-wider text-emerald-700">Important</p>
          <h1 className="mt-2 text-4xl font-black text-slate-950">Disclaimer</h1>
          <div className="mt-6 space-y-7 text-sm leading-7 text-slate-700 sm:text-base">
            <p>HaqSathi AI is a guidance and drafting tool. Please read this before relying on anything generated by the platform.</p>
            <section><h2 className="text-2xl font-black text-slate-950">We are not an official authority</h2><p className="mt-2">HaqSathi AI is <b>not</b> a government department, regulator, bank, police authority, court, or law firm, and has no official standing with RBI, NPCI, consumer forums, RTI authorities, or any scheme administrator.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">AI-generated content can be wrong</h2><p className="mt-2">All drafts, risk scores, eligibility suggestions, checklists and action plans are AI-generated and may be incomplete, outdated, or incorrect. <b>Always cross-check against the official source</b> — your bank&apos;s app/website, the company&apos;s support, the relevant government portal, or a qualified professional — before acting on or submitting anything.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">No guaranteed outcomes</h2><p className="mt-2">We do not guarantee that any refund, complaint resolution, scheme approval, or dispute outcome will result from using our drafts or plans.</p></section>
            <FraudEscalationAlert />
            <section><h2 className="text-2xl font-black text-slate-950">Not legal advice</h2><p className="mt-2">Tools like &quot;Legal Notice Style Draft&quot; or &quot;RTI Application Helper&quot; produce template-style drafts for reference only. They are not legal advice, and using them creates no advocate-client or professional relationship.</p></section>
            <section><h2 className="text-2xl font-black text-slate-950">Third-party links and services</h2><p className="mt-2">We may link to or rely on third-party services such as banks, government portals and payment processors. We are not responsible for their content, availability, or practices.</p></section>
          </div>
          <div className="mt-8 flex flex-wrap gap-3"><Link href="/upi-help" className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">UPI Help</Link><Link href="/" className="rounded-xl border px-5 py-3 font-semibold">Home</Link></div>
        </div>
      </article>
    </main>
  )
}
